import React, { useEffect, useState } from 'react';
import { Settings as SettingsIcon, Save, ShieldCheck, Bell, Download, Upload, Palette, KeyRound, Building2, CalendarDays, LockKeyhole, Database, Trash2, RefreshCw, AlertTriangle, FolderOpen, CheckCircle, HardDrive } from 'lucide-react';
import { AcademySettings } from '../types';
import { soundAlertManager } from '../utils/soundAlert';
import * as XLSX from 'xlsx';
import { SystemToast, SystemToastType } from '../components/SystemToast';
import { getDesktopNotificationPermission, requestDesktopNotificationPermission, sendDesktopNotification } from '../utils/desktopNotifier';
import { updateAdminCredentials } from '../services/api';
import { isDesktopApp } from '../services/localDb';

interface SettingsViewProps {
  settings: AcademySettings;
  onSaveSettings: (settings: AcademySettings) => void | Promise<void>;
  onResetData: () => Promise<void>;
  onExportAllData: () => void;
  onImportAllData?: (data: any) => void;
  onStartNewMonth?: () => void;
  isDbConnected?: boolean;
  currentUsername?: string;
  onCredentialsChanged?: (username: string) => void;
}

type AcademyPrefs = { monthlySessions:number; expiryWarningDays:number; oneSessionWarning:boolean; expiryWarning:boolean; expiredWarning:boolean };
const readLocal=<T,>(key:string,fallback:T):T=>{try{const r=localStorage.getItem(key);return r?JSON.parse(r):fallback}catch{return fallback}};

export const SettingsView: React.FC<SettingsViewProps> = ({settings,onSaveSettings,onResetData,onExportAllData,onImportAllData,onStartNewMonth,isDbConnected,currentUsername='admin',onCredentialsChanged}) => {
  const [formData,setFormData]=useState<AcademySettings>(settings);
  const [tab,setTab]=useState<'academy'|'subscriptions'|'notifications'|'appearance'|'backup'|'account'>('academy');
  const [saved,setSaved]=useState(false); const [resetOpen,setResetOpen]=useState(false); const [resetting,setResetting]=useState(false);
  const [prefs,setPrefs]=useState<AcademyPrefs>(()=>readLocal('ifc_academy_prefs',{monthlySessions:8,expiryWarningDays:7,oneSessionWarning:true,expiryWarning:true,expiredWarning:true}));
  const [username,setUsername]=useState(currentUsername||'admin'); const [currentPassword,setCurrentPassword]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [savingAccount,setSavingAccount]=useState(false);
  const [desktopPermission,setDesktopPermission]=useState(getDesktopNotificationPermission()); const [dbPath,setDbPath]=useState(''); const [syncing,setSyncing]=useState(false);
  const [toast,setToast]=useState<{open:boolean;type:SystemToastType;title:string;message?:string}>({open:false,type:'success',title:''});

  useEffect(()=>setFormData(settings),[settings]); useEffect(()=>setUsername(currentUsername||'admin'),[currentUsername]); useEffect(()=>localStorage.setItem('ifc_academy_prefs',JSON.stringify(prefs)),[prefs]);
  const showToast=(type:SystemToastType,title:string,message?:string)=>{setToast({open:true,type,title,message});window.setTimeout(()=>setToast(x=>({...x,open:false})),3500)};
  const save=async(e?:React.FormEvent)=>{e?.preventDefault();localStorage.setItem('ifc_academy_prefs',JSON.stringify(prefs));await onSaveSettings(formData);setSaved(true);soundAlertManager.playSuccessTone();setTimeout(()=>setSaved(false),2500)};
  const saveAccount=async()=>{if(!username.trim())return showToast('error','اسم المستخدم مطلوب');if(password.length<6)return showToast('error','كلمة المرور يجب أن تكون 6 أحرف/أرقام على الأقل');if(password!==confirm)return showToast('error','تأكيد كلمة المرور غير مطابق');try{setSavingAccount(true);const r=await updateAdminCredentials(username.trim(),password,currentPassword);setCurrentPassword('');setPassword('');setConfirm('');onCredentialsChanged?.(r.username);showToast('success','تم تحديث بيانات الدخول','تم حفظ بيانات الدخول محليًا ومزامنتها مع Supabase عند توفر الاتصال.')}catch(e:any){showToast('error','تعذر تحديث بيانات الدخول',e?.message||'حاول مرة أخرى.')}finally{setSavingAccount(false)}};
  const requestDesktop=async()=>{const ok=await requestDesktopNotificationPermission();setDesktopPermission(getDesktopNotificationPermission());if(ok){setFormData(x=>({...x,desktopNotificationsEnabled:true}));sendDesktopNotification({title:formData.academyName||'IFC Academy',body:'تم تفعيل إشعارات سطح المكتب.',playSound:true,soundType:'success'})}};
  const makeDataFolder=async()=>{if(!isDesktopApp()){showToast('success','نسخة الويب','النسخة المحلية في المتصفح محفوظة داخل IndexedDB ولا تحتاج ملف SQLite.');return;}try{setSyncing(true);const fs=await import('@tauri-apps/plugin-fs');await fs.mkdir('IFC Academy Data',{baseDir:fs.BaseDirectory.Document,recursive:true});let db:Uint8Array|null=null;for(const dir of [fs.BaseDirectory.AppData,fs.BaseDirectory.AppConfig,fs.BaseDirectory.Data]){try{db=await fs.readFile('ifc_academy.db',{baseDir:dir});break}catch{}}if(!db)throw new Error('ملف قاعدة البيانات الحية غير موجود بعد.');await fs.writeFile('IFC Academy Data/ifc_academy.db',db,{baseDir:fs.BaseDirectory.Document});setDbPath('Documents / IFC Academy Data / ifc_academy.db');showToast('success','تم تحديث مجلد البيانات','تم إنشاء نسخة SQLite قابلة للفتح والنسخ من مجلد بيانات الأكاديمية.')}catch(e:any){showToast('error','تعذر تجهيز مجلد البيانات',e?.message||'تأكد من صلاحيات التطبيق.')}finally{setSyncing(false)}};
  const importBackup=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=async ev=>{try{const wb=XLSX.read(new Uint8Array(ev.target?.result as ArrayBuffer),{type:'array',cellDates:true});const sheets:Record<string,any[]>= {};wb.SheetNames.forEach(n=>sheets[n]=XLSX.utils.sheet_to_json(wb.Sheets[n],{defval:'',raw:true}));await onImportAllData?.({__format:'ifc-excel-v2',...sheets});showToast('success','تم استيراد النسخة','تم إرسال البيانات للاسترجاع إلى قاعدة SQLite المحلية.')}catch(err:any){showToast('error','تعذر الاسترجاع',err?.message||'ملف النسخة غير صالح.')}finally{e.target.value=''}};reader.readAsArrayBuffer(file)};
  const tabs=[['academy','الأكاديمية',Building2],['subscriptions','الاشتراكات',CalendarDays],['notifications','الإشعارات',Bell],['appearance','المظهر',Palette],['backup','البيانات والنسخ',Database],['account','بيانات الدخول',KeyRound]] as const;
  return <div id="view-settings" className="space-y-5 animate-fadeIn pb-12 max-w-6xl" dir="rtl">
    <div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-2xl bg-blue-500/15 border border-blue-500/30 flex items-center justify-center text-blue-400"><SettingsIcon className="w-5 h-5"/></div><div><h1 className="text-xl font-black text-white">إعدادات الأكاديمية والنظام</h1><p className="text-xs text-slate-400 mt-1">الإعدادات الأساسية، الاشتراكات، الإشعارات، المظهر، قاعدة البيانات وبيانات الدخول.</p></div></div><span className={`text-[11px] font-bold px-3 py-1.5 rounded-full border ${isDbConnected?'text-emerald-300 bg-emerald-500/10 border-emerald-500/20':'text-rose-300 bg-rose-500/10 border-rose-500/20'}`}>{isDbConnected?'● قاعدة البيانات المحلية تعمل':'● مشكلة في قاعدة البيانات المحلية'}</span></div>
    <div className="grid grid-cols-2 md:grid-cols-6 gap-2 p-2 rounded-2xl bg-white/[0.03] border border-white/10">{tabs.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setTab(id)} className={`px-3 py-3 rounded-xl text-xs font-bold flex items-center justify-center gap-2 ${tab===id?'bg-blue-600 text-white shadow-lg':'text-slate-400 hover:text-white hover:bg-white/[0.05]'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div>
    <form onSubmit={save} className="space-y-5">
      {tab==='academy'&&<><Section title="بيانات الأكاديمية" icon={<Building2 className="w-4 h-4 text-blue-400"/>}><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="اسم الأكاديمية"><input value={formData.academyName} onChange={e=>setFormData({...formData,academyName:e.target.value})}/></Field><Field label="اسم العرض / الشعار"><input value={formData.logoText} onChange={e=>setFormData({...formData,logoText:e.target.value})}/></Field><Field label="الهاتف"><input value={formData.phone} onChange={e=>setFormData({...formData,phone:e.target.value})}/></Field><Field label="البريد الإلكتروني"><input value={formData.email} onChange={e=>setFormData({...formData,email:e.target.value})}/></Field><Field label="العنوان"><input value={formData.address} onChange={e=>setFormData({...formData,address:e.target.value})}/></Field><Field label="العملة"><input value={formData.currency} onChange={e=>setFormData({...formData,currency:e.target.value})}/></Field><Field label="الموسم الحالي"><input value={formData.currentSeason} onChange={e=>setFormData({...formData,currentSeason:e.target.value})}/></Field></div></Section></>}
      {tab==='subscriptions'&&<Section title="إعدادات الاشتراكات والتنبيهات" icon={<CalendarDays className="w-4 h-4 text-amber-400"/>}><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="عدد حصص الشهر الافتراضي"><input type="number" min={1} max={31} value={prefs.monthlySessions} onChange={e=>setPrefs({...prefs,monthlySessions:Math.max(1,Number(e.target.value)||8)})}/></Field><Field label="التنبيه قبل انتهاء الاشتراك بعدد أيام"><input type="number" min={1} max={30} value={prefs.expiryWarningDays} onChange={e=>setPrefs({...prefs,expiryWarningDays:Math.max(1,Math.min(30,Number(e.target.value)||7))})}/></Field></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4"><Toggle label="قرب انتهاء الاشتراك" checked={prefs.expiryWarning} onChange={v=>setPrefs({...prefs,expiryWarning:v})}/><Toggle label="اشتراك منتهي" checked={prefs.expiredWarning} onChange={v=>setPrefs({...prefs,expiredWarning:v})}/><Toggle label="حصة واحدة متبقية" checked={prefs.oneSessionWarning} onChange={v=>setPrefs({...prefs,oneSessionWarning:v})}/></div></Section>}
      {tab==='notifications'&&<Section title="مركز الإشعارات" icon={<Bell className="w-4 h-4 text-yellow-400"/>}><p className="text-xs text-slate-300 leading-6">كل الإشعارات التشغيلية محفوظة في القاعدة المحلية، وتشترك كل الصفحات في مركز واحد: قرب انتهاء الاشتراك، انتهاء الاشتراك، عمليات النظام، إضافة/تعديل/حذف لاعب أو مدرب، التجديدات، صرف الرواتب والمصروفات. زر سلة المهملات داخل مركز الإشعارات يسمح بالنقل والاستعادة والحذف النهائي.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-3"><Toggle label="إشعارات سطح المكتب" checked={formData.desktopNotificationsEnabled!==false} onChange={v=>setFormData({...formData,desktopNotificationsEnabled:v})}/><Toggle label="إشعارات WhatsApp/التنبيهات المساعدة" checked={formData.whatsappNotificationsEnabled} onChange={v=>setFormData({...formData,whatsappNotificationsEnabled:v})}/></div><button type="button" onClick={requestDesktop} className="btn-blue mt-3">تفعيل إشعارات Windows {desktopPermission==='granted'?'✓':''}</button></Section>}
      {tab==='appearance'&&<Section title="المظهر والهوية" icon={<Palette className="w-4 h-4 text-purple-400"/>}><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="اللون الأساسي"><input type="color" value={formData.primaryColor||'#2563eb'} onChange={e=>setFormData({...formData,primaryColor:e.target.value})}/></Field><Field label="لون الخلفية"><input type="color" value={formData.backgroundColor||'#020617'} onChange={e=>setFormData({...formData,backgroundColor:e.target.value})}/></Field><Field label="لون الشريط"><input type="color" value={formData.navbarColor||'#0b1120'} onChange={e=>setFormData({...formData,navbarColor:e.target.value})}/></Field></div><p className="text-xs text-slate-400">تغيير الألوان يتم حفظه في القاعدة المحلية ويزامن تلقائيًا مع Supabase عند توفر الاتصال.</p></Section>}
      {tab==='backup'&&<><Section title="قاعدة البيانات المحلية" icon={<Database className="w-4 h-4 text-emerald-400"/>}><div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-xs text-emerald-100 leading-6">قاعدة التشغيل محلية أولًا: SQLite داخل Windows Tauri، وIndexedDB داخل Web. عند وجود الإنترنت تكون Supabase هي النسخة الرئيسية وتتم المزامنة تلقائيًا، وعند انقطاعه يستمر البرنامج محليًا ثم يرفع التغييرات عند عودة الاتصال.</div><div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-3"><div className="p-4 rounded-xl bg-white/[0.03] border border-white/10"><div className="text-[10px] text-slate-500">ملف قاعدة البيانات الأساسي</div><div className="font-mono text-xs text-white mt-1">ifc_academy.db</div></div><div className="p-4 rounded-xl bg-white/[0.03] border border-white/10"><div className="text-[10px] text-slate-500">مجلد البيانات للعميل والمبرمج</div><div className="font-mono text-xs text-white mt-1 break-all">{dbPath||'اضغط تجهيز مجلد البيانات'}</div></div></div><button type="button" disabled={syncing} onClick={makeDataFolder} className="btn-green mt-3"><FolderOpen className="w-4 h-4"/>{syncing?'جارٍ تجهيز النسخة...':'تجهيز مجلد بيانات IFC Academy'}</button></Section><Section title="نسخة Excel" icon={<HardDrive className="w-4 h-4 text-blue-400"/>}><div className="flex flex-wrap gap-3"><button type="button" onClick={onExportAllData} className="btn-blue"><Download className="w-4 h-4"/> تصدير نسخة كاملة Excel</button><label className="btn-green cursor-pointer"><Upload className="w-4 h-4"/> استرجاع Excel<input type="file" accept=".xlsx,.xls" className="hidden" onChange={importBackup}/></label></div></Section><Section title="دورة الشهر والمنطقة الخطرة" icon={<AlertTriangle className="w-4 h-4 text-amber-400"/>}><button type="button" onClick={onStartNewMonth} className="btn-amber"><RefreshCw className="w-4 h-4"/> بدء دورة شهر جديدة</button><button type="button" onClick={()=>setResetOpen(true)} className="btn-danger mr-2"><Trash2 className="w-4 h-4"/> تصفير بيانات الأكاديمية</button></Section></>}
      {tab==='account'&&<><Section title="اسم المستخدم وكلمة المرور" icon={<KeyRound className="w-4 h-4 text-amber-400"/>}><div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs text-amber-100 leading-6">SQLite هي قاعدة التشغيل المحلية. عند عدم وجود إنترنت يتم تغيير الباسورد محليًا وتسجيل التغيير للمزامنة، وعند عودة الإنترنت يتم تحديث Supabase Auth تلقائيًا. كلمة المرور لا تُحفظ كنص مكشوف داخل SQLite.</div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="اسم المستخدم"><input value={username} onChange={e=>setUsername(e.target.value)}/></Field><Field label="كلمة المرور الحالية"><input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="مطلوبة للمزامنة"/></Field><Field label="كلمة المرور الجديدة"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="6 أحرف/أرقام على الأقل"/></Field><Field label="تأكيد كلمة المرور"><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></Field></div><button type="button" disabled={savingAccount} onClick={saveAccount} className="btn-blue mt-3"><KeyRound className="w-4 h-4"/>{savingAccount?'جارٍ الحفظ...':'حفظ بيانات الدخول'}</button></Section><Section title="الأمان" icon={<ShieldCheck className="w-4 h-4 text-rose-400"/>}><p className="text-xs text-slate-300 leading-6">يوجد قفل تلقائي للجلسة عند عدم النشاط، وتأكيد للعمليات الخطرة. إعدادات الأداء القديمة مثل Cache والأصوات وتقليل الحركات تم إخراجها من صفحة الإعدادات كما طلبت.</p></Section></>}
      <div className="flex justify-end items-center gap-3">{saved&&<span className="text-xs text-emerald-400 font-bold flex items-center gap-1"><CheckCircle className="w-4 h-4"/> تم الحفظ</span>}<button type="submit" className="btn-blue"><Save className="w-4 h-4"/> حفظ الإعدادات</button></div>
    </form>
    {resetOpen&&<div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4"><div className="max-w-md w-full bg-slate-900 border border-rose-500/30 rounded-2xl p-6 text-center space-y-4"><LockKeyhole className="w-10 h-10 text-rose-400 mx-auto"/><h3 className="text-lg font-black text-white">تأكيد تصفير البيانات</h3><p className="text-xs text-slate-300 leading-6">سيتم حذف بيانات اللاعبين والمدربين والحضور والمدفوعات والمصروفات والإشعارات من SQLite. خذ نسخة قبل التنفيذ.</p><div className="flex justify-center gap-2"><button type="button" onClick={()=>setResetOpen(false)} className="btn-gray">إلغاء</button><button type="button" disabled={resetting} onClick={async()=>{setResetting(true);try{await onResetData();setResetOpen(false);showToast('success','تم تصفير البيانات')}catch(e:any){showToast('error','تعذر التصفير',e?.message)}finally{setResetting(false)}}} className="btn-danger">{resetting?'جارٍ التنفيذ...':'تأكيد التصفير'}</button></div></div></div>}
    <SystemToast open={toast.open} type={toast.type} title={toast.title} message={toast.message} onClose={()=>setToast(x=>({...x,open:false}))}/>
    <style>{`.btn-blue,.btn-gray,.btn-green,.btn-amber,.btn-danger{display:inline-flex;align-items:center;gap:.45rem;padding:.65rem .9rem;border-radius:.75rem;font-size:.72rem;font-weight:800;transition:.2s}.btn-blue{background:rgba(37,99,235,.18);color:#bfdbfe;border:1px solid rgba(59,130,246,.3)}.btn-gray{background:rgba(255,255,255,.06);color:#cbd5e1;border:1px solid rgba(255,255,255,.12)}.btn-green{background:rgba(16,185,129,.16);color:#a7f3d0;border:1px solid rgba(16,185,129,.3)}.btn-amber{background:rgba(245,158,11,.15);color:#fde68a;border:1px solid rgba(245,158,11,.3)}.btn-danger{background:rgba(244,63,94,.12);color:#fda4af;border:1px solid rgba(244,63,94,.3)}.btn-blue:hover,.btn-gray:hover,.btn-green:hover,.btn-amber:hover,.btn-danger:hover{filter:brightness(1.15)}input,select{width:100%;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:.75rem;padding:.7rem .8rem;color:white;outline:none;font-size:.78rem}input:focus,select:focus{border-color:rgba(96,165,250,.7)}`}</style>
  </div>
};
const Section:React.FC<{title:string;icon:React.ReactNode;children:React.ReactNode}>=({title,icon,children})=><div className="bg-white/[0.04] border border-white/10 rounded-2xl p-5 shadow-xl shadow-black/10 space-y-4"><div className="flex items-center gap-2 border-b border-white/10 pb-3"><span>{icon}</span><h3 className="text-sm font-black text-white">{title}</h3></div>{children}</div>;
const Field:React.FC<{label:string;children:React.ReactNode}>=({label,children})=><label className="block"><span className="block text-xs text-slate-300 mb-1.5 font-bold">{label}</span>{children}</label>;
const Toggle:React.FC<{label:string;checked:boolean;onChange:(v:boolean)=>void}>=({label,checked,onChange})=><label className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/10 cursor-pointer"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="w-4 h-4"/><span className="text-xs font-bold text-slate-200">{label}</span></label>;
